version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGODB_DATABASE=uala-mgo
    networks:
      - app-network
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Puerto para la aplicación
      - "15672:15672" # Puerto para el panel de administración
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
